apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-auth
  labels:
    app: fc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-auth
  template:
    metadata:
      labels:
        app: fc-auth
    spec:
      containers:
        - name: fc-auth
          image: sthanguy/fc-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: managed-secret 
                  key: DSN
                  optional: false
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: managed-secret
                  key: GITHUB_CLIENT_ID
                  optional: false
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: managed-secret
                  key: GITHUB_CLIENT_SECRET
                  optional: false
            - name: CALLBACK_URL_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: managed-secret
                  key: CALLBACK_URL_PROTOCOL
                  optional: false
            - name: CALLBACK_URL_HOST
              valueFrom:
                secretKeyRef:
                  name: managed-secret
                  key: CALLBACK_URL_HOST
                  optional: false
            - name: CALLBACK_URL_PORT
              valueFrom:
                secretKeyRef:
                  name: managed-secret
                  key: CALLBACK_URL_PORT
                  optional: false
            - name: COOKIE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: managed-secret
                  key: COOKIE_DOMAIN
                  optional: false
