apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-auth
  labels:
    app: fc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-auth
  template:
    metadata:
      labels:
        app: fc-auth
    spec:
      containers:
        - name: fc-auth
          image: sthanguy/fc-auth:latest