apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: infisical-auth-token
  annotations:
    kubernetes.io/service-account.name: "infisical-auth"

# link secret to role
# kubectl patch serviceaccount infisical-auth -p '{"secrets": [{"name": "infisical-auth-token"}]}' -n default
# ^ make sure to use git bash

# fetch secret
# kubectl get secret infisical-auth-token -n default -o=jsonpath='{.data.token}' | base64 --decode

# configuring kubernetes auth:
# https://infisical.com/docs/documentation/platform/identities/kubernetes-auth