apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: ampq
    protocol: TCP
    port: 5672
  - name: management-ui
    protocol: TCP
    port: 15672
    targetPort: 15672
