apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./auth/kustomization.yaml
  - ./gateway/kustomization.yaml
  - ./infisical/kustomization.yaml
  - ./postgres/kustomization.yaml
  - ./projects/kustomization.yaml
  - ./rabbitmq/kustomization.yaml
  - ./session-cache/kustomization.yaml
