apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ./auth/
- ./gateway/
- ./infisical/
- ./postgres/
- ./projects/
- ./rabbitmq/
- ./session-cache/
patches:
  - path: infisicalsecret-patch.yaml
    target:
      version: v1alpha1
      kind: InfisicalSecret
      name: infisicalsecret
